openapi: 3.0.0
info:
  title: 'Laravel and Swagger'
  description: 'Getting started with Laravel and Swagger'
  termsOfService: ''
  contact:
    email: name@example.com
  version: 1.0.0
paths:
  /create:
    get:
      description: 'Return a user''s first and last name'
      operationId: 'App\Http\Controllers\UserController::create'
      parameters:
        -
          name: firstname
          in: query
          description: 'Your first name'
          required: true
          type: string
        -
          name: lastname
          in: query
          description: 'Your last name'
          required: true
          type: string
      responses:
        '200':
          description: OK
        '422':
          description: 'Missing Data'
